name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: Aurora v${{ env.VERSION }}
        draft: false
        prerelease: false
        files: |
          build/libs/aurora-${{ env.VERSION }}.jar
          build/libs/aurora-${{ env.VERSION }}-dev.jar
          build/libs/aurora-${{ env.VERSION }}-sources.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
